prezento/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    devise_for :users
    get 'users/:user_id/projects' => 'users#projects', as: :user_projects

    resources :projects do
      resources :repositories, only: [:new, :create]
    end

    resources :repositories, except: [:update]
    get '/repositories/:id/modules/:module_result_id' => 'repositories#show', as: :repository_module
    get '/repositories/:id/state' => 'repositories#state', as: :repository_state
    get '/repositories/:id/state_with_date' => 'repositories#state_with_date', as: :repository_state_with_date
    put '/repositories/:id' => 'repositories#update', as: :repository_update
    get '/repositories/:id/process' => 'repositories#process_repository', as: :repository_process
    get '/repository_branches' => 'repositories#branches', as: :repository_branches

    scope :format => false, :constraints => { :format => 'json' } do
      post '/repositories/:id/notify_push' => 'repositories#notify_push', as: :repository_notify_push, format: :json
    end

    resources :kalibro_configurations do
      get '/metric_configurations/choose_metric' => 'metric_configurations#choose_metric', as: :choose_metric
      resources :metric_configurations, except: [:update, :new] do
        get '/kalibro_ranges/new' => 'kalibro_ranges#new', as: :new_kalibro_range
        resources :kalibro_ranges, except: [:update, :new]
        put '/kalibro_ranges/:id' => 'kalibro_ranges#update', as: :kalibro_range_update
      end
      post '/metric_configurations/new' => 'metric_configurations#new', as: :new_metric_configuration
      put '/metric_configurations/:id' => 'metric_configurations#update', as: :metric_configuration_update

      resources :compound_metric_configurations, except: [:destroy, :update]
      put '/compound_metric_configurations/:id' => 'compound_metric_configurations#update', as: :compound_metric_configuration_update

      resources :hotspot_metric_configurations, only: [:create]
    end

    resources :reading_groups do
      resources :readings, except: [:index, :update, :show]
      put '/readings/:id' => 'readings#update', as: :reading_update
    end

    post '/modules/:id/metric_history' => 'modules#metric_history', as: 'module_metric_history'
    post '/modules/:id/tree' => 'modules#load_module_tree', as: 'module_tree'

    root "home#index"
  end

end

prezento/app/models/repository.rb
class Repository < KalibroClient::Entities::Processor::Repository
  include KalibroRecord
  include HasOwner

  attr_writer :attributes

  def attributes
    @attributes ||= RepositoryAttributes.find_by_repository_id(@id)
  end

  def destroy
    self.attributes.destroy unless self.attributes.nil?
    @attributes = nil
    super
  end
end

prezento/app/controllers/repositories_controller.rb
require 'webhooks'

include OwnershipAuthentication

class RepositoriesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :state, :state_with_date, :index, :notify_push]
  before_action :project_owner?, only: [:new, :create], unless: Proc.new { params[:project_id].nil? }
  before_action :repository_owner?, only: [:edit, :update, :destroy, :process_repository]
  before_action :set_repository, only: [:show, :edit, :update, :destroy, :state, :state_with_date, :process_repository,
                                        :notify_push]
  before_action :set_project_id_repository_types_and_configurations, only: [:new, :edit]

  # Gitlab can't send a CSRF token, don't require one
  skip_before_action :verify_authenticity_token, :only => [:notify_push]

  def index
    @repositories = Repository.public_or_owned_by_user(current_user)
  end

  # GET /projects/1/repositories/1
  # GET /projects/1/repositories/1.json
  # GET /projects/1/repositories/1/modules/1
  # GET /projects/1/repositories/1/modules/1.json
  def show
    set_kalibro_configuration
  end

  # GET projects/1/repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit; end

  # POST /projects/1/repositories
  # POST /projects/1/repositories.json
  def create
    @repository = Repository.new(repository_params)
    respond_to do |format|
      create_and_redir(format)
    end
  end

  # PUT /projects/1/repositories/1
  # PUT /projects/1/repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to(repository_path(@repository.id), notice: t('successfully_updated', :record => t(@repository.class))) }
        format.json { head :no_content }
      else
        failed_action(format, 'edit')
      end
    end
  end

  # DELETE /projects/1/repositories/1
  # DELETE /projects/1/repositories/1.json
  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.json { head :no_content }
    end
  end

  # POST /projects/1/repositories/1/state
  def state
    if params[:last_state] != 'READY'
      @processing = @repository.last_processing

      respond_to_processing_state
    else
      head :ok, :content_type => 'text/html' # Just don't do anything
    end
  end

  # POST /projects/1/repositories/1/state_with_date
  def state_with_date
    year, month, day = params[:year], params[:month], params[:day]
    @processing = @repository.processing_with_date("#{year}-#{month}-#{day}")

    respond_to_processing_state
  end

  # GET /projects/1/repositories/1/process
  def process_repository
    @repository.process
    set_kalibro_configuration
    respond_to do |format|
      format.html { redirect_to repository_path(@repository.id) }
    end
  end

  def branches
    branch_params = branches_params
    branches_list = Repository.branches(branch_params[:url], branch_params[:scm_type])

    respond_to do |format|
      format.json { render json: branches_list }
    end
  end

  def notify_push
    hook_info = Webhooks::GitLab.new(request, @repository)
    if hook_info.valid_request?
      if hook_info.valid_address?
        if hook_info.valid_branch?
          @repository.cancel_processing_of_repository unless %w(READY ERROR).include? @repository.last_processing_state
          @repository.process
        end

        render nothing: true, status: :ok
      else
        render nothing: true, status: :forbidden
      end
    else
      render nothing: true, status: :unprocessable_entity
    end
  end

  private
  def set_project_id_repository_types_and_configurations
    @project_id = params[:project_id]
    @repository_types = Repository.repository_types
    @configurations = KalibroConfiguration.public_or_owned_by_user(current_user).map { |conf|
      [conf.name, conf.id]
    }
  end

  # Duplicated code on create and update actions extracted here
  def failed_action(format, destiny_action)
    set_project_id_repository_types_and_configurations

    format.html { render action: destiny_action }
    format.json { render json: @repository.errors, status: :unprocessable_entity }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_repository
    @repository = Repository.find(params[:id].to_i)
  end

  def set_kalibro_configuration
    if @repository
      @kalibro_configuration = KalibroConfiguration.find(@repository.kalibro_configuration_id)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def repository_params
    params[:repository][:name].strip!
    params[:repository][:address].strip!
    params[:repository][:project_id] = params[:project_id] if params.key? :project_id
    params[:repository]
  end

  def branches_params
    params.permit(:scm_type, :url)
  end

  # Code extracted from create action
  def create_and_redir(format)
    if @repository.save
      current_user.repository_attributes.create(repository_id: @repository.id)
      format.html { redirect_to repository_process_path(@repository.id), notice: t('successfully_created', :record => t(@repository.class)) }
    else
      failed_action(format, 'new')
    end
  end

  def respond_to_processing_state
    respond_to do |format|
      if @processing.state == 'READY'
        format.js { render action: 'load_ready_processing' }
      elsif @processing.state == 'ERROR'
        format.js { render action: 'load_error' }
      else
        format.js { render action: 'reload_processing' }
      end
    end
  end
end

prezento/app/helpers/repository_helper.rb
module RepositoryHelper
  def periodicity_options
    [[t('not_periodically'), 0], [t('one_day'), 1], [t('two_days'), 2], [t('weekly'), 7], [t('biweekly'), 15], [t('monthly'), 30]]
  end

  def license_options
   YAML.load_file("config/licenses.yml").split("; ")
  end

  def periodicity_option(periodicity)
    periodicity_label = periodicity_options.select {|option| option.last == periodicity}.first
    unless periodicity_label.nil?
      return periodicity_label.first
    end
  end

  def day_options
    (1..31).to_a.map {|day| [day, day]}
  end

  def month_options
    (1..12).to_a.map {|month| [month, month]}
  end

  def year_options
    # FIXME: this will not work some years from now
    (2013..2020).to_a.map {|year| [year, year]}
  end

  def repository_owner? repository_id
    user_signed_in? && !current_user.repository_attributes.find_by_repository_id(repository_id).nil?
  end
end

prezento/app/views/repositories/_form.html.erb
<%= render :partial => 'shared/form_errors', :locals => {:object => @repository} %>


<div class="row margin-left-none">
  <div class="form-table col-md-9">

    <div class="form-row">
      <div class="field-container">
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, :required => true, class: 'text-field form-control' %>
      </div>
      <div class="help-container">
        <p>
          <%= t('activemodel.hints.repository.name') %>
        </p>
      </div>
    </div>

    <div class="form-row">
      <div class="field-container">
        <%= f.label :description, class: 'control-label' %>
        <%= f.text_area :description, class: 'text-area form-control' %>
      </div>
      <div class="help-container">
        <p>
          <%= t('activemodel.hints.repository.description') %>
        </p>
      </div>
    </div>

    <div class="form-row">
      <div class="field-container">
        <%= f.label :license, class: 'control-label' %>
        <%= f.select( :license, license_options, class: 'text-area form-control' ) %>
      </div>
      <div class="help-container">
        <p>
          <%= t('activemodel.hints.repository.license') %>
        </p>
      </div>
    </div>

    <div class="form-row">
      <div class="field-container">
        <%= f.label :scm_type, class: 'control-label' %>
        <%= f.select( :scm_type, @repository_types, {}, class: 'tooltip-control', onchange: "_repository_branch.toggle();" ) %>
      </div>
      <div class="help-container">
        <p>
          <%= t('activemodel.hints.repository.scm_type') %>
        </p>
      </div>
    </div>

    <div class="form-row">
      <div class="field-container">
        <%= f.label :address, class: 'control-label' %>
        <%= f.text_field :address, :required => true, class: 'text-field form-control', onchange: "_repository_branch.fetch(this.value);" %>
      </div>
      <div class="help-container">
        <p>
          <%= t('activemodel.hints.repository.address') %>
        </p>
      </div>
    </div>

    <div id="branches">
      <div class="form-row">
        <div class="field-container">
          <%= f.label :branch, class: 'control-label' %>
          <%= f.select :branch, []%>
        </div>
        <div class="help-container">
          <p>
            <%= t('activemodel.hints.repository.address') %>
          </p>
        </div>
      </div>
    </div>

    <div class="form-row">
      <div class="field-container">
        <%= f.label :period, class: 'control-label' %>
        <%= f.select( :period, periodicity_options, class: 'tooltip-control' ) %>
      </div>
      <div class="help-container">
        <p>
          <%= t('activemodel.hints.repository.period') %>
        </p>
      </div>
    </div>

    <div class="form-row">
      <div class="field-container">
        <%= f.label :kalibro_configuration_id, KalibroConfiguration.model_name.human, class: 'control-label' %>
        <%= f.select( :kalibro_configuration_id, @configurations, class: 'tooltip-control' ) %>
      </div>
      <div class="help-container">
        <p>
          <%= t('activemodel.hints.repository.kalibro_configuration', configuration_href: link_to(KalibroConfiguration.model_name.human, "http://mezuro.github.io/tutorial/2016/04/04/tutorial-keywords.html#configuration", target: "_blank")).html_safe %>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="row margin-left-none" style="margin-top: 20px">
  <%= f.submit t('save'), class: 'btn btn-primary' %>
  <%= link_to t('back'),  projects_path, class: 'btn btn-default' %>
</div>

<script type="text/javascript">
  var _repository_branch = new Repository.Branch;
</script>

prezento/app/views/repositories/_hotspot_metric_results_error.html.erb
<p><%= t('activemodel.errors.repository.no_hotspot_metric_results') %></p>

prezento/app/views/repositories/_metric_results_error.html.erb
<p><%= t('activemodel.errors.repository.no_metric_results') %></p>

prezento/app/views/repositories/_module_tree_error.html.erb
<p><%= t('activemodel.errors.repository.no_module_tree') %></p>

prezento/app/views/repositories/_processing_information.html.erb
<p>
  <strong><%= t('activemodel.attributes.processing.state') %>:</strong>
  <%= @processing.state %>
</p>

<p>
  <strong><%= t('activemodel.attributes.processing.creation_date') %>:</strong>
  <%= @processing.created_at.strftime("%Y/%m/%d at %Hh%M (%z)") %>
</p>

<% unless @processing.process_times.nil? %>
  <% @processing.process_times.each do |process_time| %>
    <p>
      <strong><%= process_time.state %> time:</strong>
      <%= humanize_elapsed_time(process_time.time) %>
    </p>
  <% end %>
<% end %>

prezento/app/views/repositories/_unstarted_processing.html.erb
<p><%= t('activemodel.errors.repository.unstarted_processing') %></p>

<div id="processing_information"><%= image_tag 'loader.gif' %> <%= t('repository.show.loading') %></div>

prezento/app/views/repositories/edit.html.erb
<div class="page-header">
  <h1><%= t_action(:edit, Repository) %></h1>
</div>

<%= form_for(@repository, :url => repository_update_path(@repository.id), method: :put) do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

prezento/app/views/repositories/index.html.erb
<div class="page-header">
  <h1><%= "#{Repository.model_name.human(count: 2)}" %></h1>
</div>

<% if user_signed_in? %>
  <p>
    <%= link_to t_action(:create, Repository), new_repository_path, class: 'btn  btn-primary' %>
  </p>
<%else%>
  <p class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= t('unauthenticated', action: t_action(:create, Repository, count: 2).downcase) %>
  </p>
<% end %>

<%= render partial: 'shared/repository_list', locals: {repositories: @repositories} %>

prezento/app/views/repositories/load_error.js.erb
$('div#processing_information').html('<%= escape_javascript(render partial: "processing_information") %>');
$('div#module_tree').html('<%= escape_javascript(render partial: "module_tree_error") %>');
$('div#hotspot_metric_results').html('<%= escape_javascript(render partial: "hotspot_metric_results_error") %>');
$('div#metric_results').html('<%= escape_javascript(render partial: "metric_results_error") %>');

prezento/app/views/repositories/load_ready_processing.js.erb
$('div#processing_information').html('<%= escape_javascript(render partial: "processing_information") %>');
Module.Tree.load("<%= escape_javascript(image_tag 'loader.gif') %> Loading data. Please, wait.", <%= @processing.root_module_result_id %>)

prezento/app/views/repositories/new.html.erb
<div class="page-header">
  <h1><%= t_action(:new, Repository) %></h1>
</div>

<% unless @project_id.nil? %>
  <%= form_for(@repository, :url => project_repositories_path(@project_id)) do |f| %>
    <%= render partial: 'form', locals: {f: f} %>
  <% end %>
<% else %>
  <%= form_for(@repository, :url => repositories_path) do |f| %>
    <%= render partial: 'form', locals: {f: f} %>
  <% end %>
<% end %>

prezento/app/views/repositories/reload_processing.js.erb
current_path_splited = window.location.pathname.split("/");
if(current_path_splited[1] != "repositories"){
  current_path_splited.splice(1,1); // Removes the locale
}
current_path = current_path_splited.join("/");

// This if prevents it from updating the repository's state after the user leaves its page
if(current_path == '<%= repository_path(id: @repository, locale: nil) %>'){
  $('div#processing_information').html('<%= escape_javascript(render partial: "processing_information") %>');
  repository = new Repository.State(<%= @repository.id %>)
  repository.schedule_poll_state('<%= @processing.state %>')
}

prezento/app/views/repositories/show.html.erb
<div class="page-header">
  <h1><%= @repository.name %></h1>
</div>

<p>
  <strong><%= Repository.human_attribute_name('description') %>:</strong>
  <%= @repository.description %>
</p>

<p>
  <strong><%= Repository.human_attribute_name('license') %>:</strong>
  <%= @repository.license %>
</p>

<p>
  <strong><%= Repository.human_attribute_name('type') %>:</strong>
  <%= @repository.scm_type %>
</p>

<p>
  <strong><%= Repository.human_attribute_name('address') %>:</strong>
  <%= @repository.address %>
</p>

<p>
  <strong><%= Repository.human_attribute_name('branch') %>:</strong>
  <%= @repository.branch %>
</p>

<p>
  <strong><%= Repository.human_attribute_name('period') %>:</strong>
  <%= periodicity_option(@repository.period) %>
</p>

<p>
  <strong><%= KalibroConfiguration.model_name.human %>:</strong>
  <%= @kalibro_configuration.name %>
</p>

<% if repository_owner? @repository.id %>
  <strong><%= t('repository.show.notify_push_url') %>:</strong>
  <input id="notify_url" value="<%= repository_notify_push_url(@repository.id) %>" readonly="">

  <button id="btn" data-clipboard-target="#notify_url">
    <i class="fa fa-copy" alt="Copy to clipboard"></i>
  </button>
<% end %>

<p><strong> <%= t('repository.show.date_processing') %>: </strong></p>

<%= form_tag(repository_state_with_date_path(@repository.id), method: "get", remote: true) do %>
  <p>
    <%= label_tag :day, t("day") %>:
    <%= select_tag(:day, options_for_select(day_options), :style => "width:55px; margin-top:5px") %>
    <%= label_tag :month, t("month") %>:
    <%= select_tag(:month, options_for_select(month_options), :style => "width:55px; margin-top:5px") %>
    <%= label_tag :year, t("year") %>:
    <%= select_tag(:year, options_for_select(year_options), :style => "width:70px; margin-top:5px") %>
    <%= submit_tag(t('search'), class: 'btn btn-info', style: 'margin-bottom:5px', onClick: "Repository.State.set_loader('#{image_tag 'loader.gif'} #{j(t('repository.show.loading'))}')") %>
  </p>
<% end %>

<hr/>

<div id="repository-accordion">
  <div id="processing-accordion">
    <h3 class="jquery-ui-accordion"><%= t('repository.show.processing_information') %></h3>
    <div id="processing_information"><%= image_tag 'loader.gif' %> <%= t('repository.show.loading') %></div>
  </div>

  <div id="module-accordion">
    <h3 class="jquery-ui-accordion"><%= t('repository.show.modules_tree') %></h3>
    <div id="module_tree"><%= image_tag 'loader.gif' %> <%= t('repository.show.loading') %></div>
  </div>

  <div id="hotspot-metric-accordion">
    <h3 class="jquery-ui-accordion"><%= t('repository.show.hotspot_metric_results') %></h3>
    <div id="hotspot_metric_results"><%= image_tag 'loader.gif' %> <%= t('repository.show.loading') %></div>
  </div>

  <div id="metric-accordion">
    <h3 class="jquery-ui-accordion"><%= t('repository.show.metric_results') %></h3>
    <div id="metric_results"><%= image_tag 'loader.gif' %> <%= t('repository.show.loading') %></div>
  </div>
</div>

<!-- Copy to clipboard -->
<%= javascript_include_tag "https://cdn.rawgit.com/zenorocha/clipboard.js/v1.5.10/dist/clipboard.min.js" %>

<script type="text/javascript">
    $(document).ready(function () {
      (new Repository.State(<%= @repository.id %>)).poll_state('');
      new Clipboard('#btn');
    });

  //Loads the accordion
  $(function() {
    $( "#repository-accordion > div" ).accordion({
      heightStyle: "content",
      collapsible: true,
    });
    $("#module-accordion").accordion({active: false})
    $("#hotspot-metric-accordion").accordion({active: false})
    $("#metric-accordion").accordion({active: false})
  });
</script>

<hr/>

<%= link_to t('back'),  repositories_path, class: 'btn btn-default' %>
<% if repository_owner? @repository.id %>
  <%= link_to t('repository.show.reprocess'), repository_process_path(@repository.id),  class: 'btn btn-info' %>
  <%= link_to t('destroy'), repository_path(@repository.id), method: :delete, data: { confirm: t('sure_destroy', model: Repository.model_name.human) }, class: 'btn btn-danger' %>
<% end %>