prezento/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    devise_for :users
    get 'users/:user_id/projects' => 'users#projects', as: :user_projects

    resources :projects do
      resources :repositories, only: [:new, :create]
    end

    resources :repositories, except: [:update]
    get '/repositories/:id/modules/:module_result_id' => 'repositories#show', as: :repository_module
    get '/repositories/:id/state' => 'repositories#state', as: :repository_state
    get '/repositories/:id/state_with_date' => 'repositories#state_with_date', as: :repository_state_with_date
    put '/repositories/:id' => 'repositories#update', as: :repository_update
    get '/repositories/:id/process' => 'repositories#process_repository', as: :repository_process
    get '/repository_branches' => 'repositories#branches', as: :repository_branches

    scope :format => false, :constraints => { :format => 'json' } do
      post '/repositories/:id/notify_push' => 'repositories#notify_push', as: :repository_notify_push, format: :json
    end

    resources :kalibro_configurations do
      get '/metric_configurations/choose_metric' => 'metric_configurations#choose_metric', as: :choose_metric
      resources :metric_configurations, except: [:update, :new] do
        get '/kalibro_ranges/new' => 'kalibro_ranges#new', as: :new_kalibro_range
        resources :kalibro_ranges, except: [:update, :new]
        put '/kalibro_ranges/:id' => 'kalibro_ranges#update', as: :kalibro_range_update
      end
      post '/metric_configurations/new' => 'metric_configurations#new', as: :new_metric_configuration
      put '/metric_configurations/:id' => 'metric_configurations#update', as: :metric_configuration_update

      resources :compound_metric_configurations, except: [:destroy, :update]
      put '/compound_metric_configurations/:id' => 'compound_metric_configurations#update', as: :compound_metric_configuration_update

      resources :hotspot_metric_configurations, only: [:create]
    end

    resources :reading_groups do
      resources :readings, except: [:index, :update, :show]
      put '/readings/:id' => 'readings#update', as: :reading_update
    end

    post '/modules/:id/metric_history' => 'modules#metric_history', as: 'module_metric_history'
    post '/modules/:id/tree' => 'modules#load_module_tree', as: 'module_tree'

    root "home#index"
  end

end

prezento/app/models/reading_group.rb
class ReadingGroup < KalibroClient::Entities::Configurations::ReadingGroup
  include KalibroRecord
  include HasOwner

  attr_writer :attributes

  def self.public
    self.public_or_owned_by_user
  end

  def attributes
    @attributes ||= ReadingGroupAttributes.find_by(reading_group_id: self.id)
  end

  def destroy
    attributes.destroy unless attributes.nil?
    @attributes = nil
    super
  end
end

prezento/app/controllers/reading_groups_controller.rb
include OwnershipAuthentication

class ReadingGroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :reading_group_owner?, only: [:edit, :update, :destroy]
  before_action :set_reading_group, only: [:show, :edit, :update, :destroy]

  # GET /reading_groups/new
  def new
    @reading_group = ReadingGroup.new
  end

  # GET /reading_groups
  # GET /reading_groups.json
  def index
    @reading_groups = ReadingGroup.public_or_owned_by_user(current_user)
  end

  # POST /reading_groups
  # POST /reading_groups.json
  def create
    @reading_group = ReadingGroup.new(reading_group_params)
    respond_to do |format|
      create_and_redir(format)
    end
  end

  # GET /reading_group/1
  # GET /reading_group/1.json
  def show; end

  # GET /reading_groups/1/edit
  # GET /reading_groups/1/edit.json
  def edit; end

  def update
    if @reading_group.update(reading_group_params)
      redirect_to(reading_group_path(@reading_group.id))
    else
      render "edit"
    end
  end

  # DELETE /reading_group/1
  # DELETE /reading_group/1.json
  def destroy
    @reading_group.destroy
    respond_to do |format|
      format.html { redirect_to reading_groups_path }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reading_group
    @reading_group = ReadingGroup.find(params[:id].to_i)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reading_group_params
    params[:reading_group][:name].strip!
    params[:reading_group]
  end

  # Extracted code from create action
  def create_and_redir(format)
    if @reading_group.save
      current_user.reading_group_attributes.create(reading_group_id: @reading_group.id)

      format.html { redirect_to reading_group_path(@reading_group.id), notice: t('successfully_created', :record => t(@reading_group.class)) }
      format.json { render action: 'show', status: :created, location: @reading_group }
    else
      format.html { render action: 'new' }
      format.json { render json: @reading_group.likeno_errors, status: :unprocessable_entity }
    end
  end
end

prezento/app/helpers/reading_groups_helper.rb
module ReadingGroupsHelper
  def reading_groups_owner? reading_group_id
    user_signed_in? && !current_user.reading_group_attributes.find_by_reading_group_id(reading_group_id).nil?
  end
end

prezento/app/views/reading_groups/_form.html.erb
<%= form_for(@reading_group, :html => { role: 'form' }) do |f| %>
  <%= render :partial => 'shared/form_errors', :locals => {:object => @reading_group} %>

<div class="row margin-left-none">
  <div class="form-table col-md-9">
    <div class="form-row">
      <div class="field-container">
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, :required => true, class: 'text-field form-control' %>
      </div>
    </div>

    <div class="form-row">
      <div class="field-container">
        <%= f.label :description, class: 'control-label' %>
        <%= f.text_area :description, class: 'text-area form-control' %>
      </div>
    </div>
  </div>
</div>

<div class="row margin-left-none" style="margin-top: 20px">
  <%= f.submit t('save'), class: 'btn btn-primary' %>
  <%= link_to t('back'), reading_groups_path, class: 'btn btn-default' %>
</div>
<% end %>

prezento/app/views/reading_groups/_no_readings.html.erb
<tr>
  <% col_number = reading_groups_owner?(@reading_group.id) ? 5 : 3 %>
  <td colspan="<%= col_number %>"><%= t('activemodel.errors.reading_group.no_readings') %></td>
</tr>

prezento/app/views/reading_groups/_reading.html.erb
<tr>
  <td><%= reading.label %></td>
  <td><%= reading.grade %></td>
  <td style="background-color: #<%= reading.color %>; width: 20%;">&nbsp;</td>
  <% if reading_groups_owner? @reading_group.id %>
    <td>
      <%= link_to t('edit'), edit_reading_group_reading_path(@reading_group.id, reading.id), class: 'btn btn-info' %>
    </td>
    <td>
      <%= link_to t('destroy'), reading_group_reading_path(@reading_group.id, reading.id), method: :delete, data: { confirm: t('sure_destroy', model: Reading.model_name.human) }, class: 'btn btn-danger' %>
    </td>
    </td>
 <% end %>
</tr>

prezento/app/views/reading_groups/edit.html.erb
<div class="page-header">
  <h1><%= t_action(:edit, ReadingGroup) %></h1>
</div>

<%= render 'form' %>

prezento/app/views/reading_groups/index.html.erb
<div class="page-header">
  <h1><%= ReadingGroup.model_name.human(count: 2) %></h1>
</div>

<% if user_signed_in? %>
  <p>
    <%= link_to t_action(:new, ReadingGroup), new_reading_group_path, class: 'btn  btn-primary' %>
  </p>
<%else%>
  <p class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= t('unauthenticated', action: t_action(:create, ReadingGroup)) %>
  </p>
<% end %>

<%= render partial: 'shared/reading_groups_list', locals: {reading_groups: @reading_groups} %>

prezento/app/views/reading_groups/new.html.erb
<div class="page-header">
  <h1><%= t_action(:new, ReadingGroup) %></h1>
</div>

<%= render 'form' %>

prezento/app/views/reading_groups/show.html.erb
<div class="page-header">
  <h1><%= @reading_group.name %></h1>
</div>

<p>
  <strong><%= ReadingGroup.human_attribute_name('description') %></strong>
  <%= @reading_group.description %>
</p>

<hr />

<h2><%= Reading.model_name.human(count: 2) %></h2>

<% if reading_groups_owner? @reading_group.id %>
  <%= link_to t_action(:new, Reading), new_reading_group_reading_path(@reading_group,), class: 'btn btn-primary' %>
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= Reading.human_attribute_name('label') %></th>
      <th><%= Reading.human_attribute_name('grade') %></th>
      <th><%= Reading.human_attribute_name('color') %></th>
    </tr>
  </thead>

  <tbody>
    <% reading_group_readings = @reading_group.readings %>
    <% if reading_group_readings.size == 0 %>
      <%= render partial: 'no_readings' %>
    <% else %>
      <%= render partial: 'reading', collection: reading_group_readings, as: :reading %>
    <% end %>
  </tbody>
</table>

<hr />

<p>
  <% if reading_groups_owner? @reading_group.id %>
    <%= link_to t('destroy'), reading_group_path(@reading_group.id), method: :delete, data: { confirm: t('sure_destroy', model: ReadingGroup.model_name.human) }, class: 'btn btn-danger' %>
  <% end %>
</p>