prezento/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    devise_for :users
    get 'users/:user_id/projects' => 'users#projects', as: :user_projects

    resources :projects do
      resources :repositories, only: [:new, :create]
    end

    resources :repositories, except: [:update]
    get '/repositories/:id/modules/:module_result_id' => 'repositories#show', as: :repository_module
    get '/repositories/:id/state' => 'repositories#state', as: :repository_state
    get '/repositories/:id/state_with_date' => 'repositories#state_with_date', as: :repository_state_with_date
    put '/repositories/:id' => 'repositories#update', as: :repository_update
    get '/repositories/:id/process' => 'repositories#process_repository', as: :repository_process
    get '/repository_branches' => 'repositories#branches', as: :repository_branches

    scope :format => false, :constraints => { :format => 'json' } do
      post '/repositories/:id/notify_push' => 'repositories#notify_push', as: :repository_notify_push, format: :json
    end

    resources :kalibro_configurations do
      get '/metric_configurations/choose_metric' => 'metric_configurations#choose_metric', as: :choose_metric
      resources :metric_configurations, except: [:update, :new] do
        get '/kalibro_ranges/new' => 'kalibro_ranges#new', as: :new_kalibro_range
        resources :kalibro_ranges, except: [:update, :new]
        put '/kalibro_ranges/:id' => 'kalibro_ranges#update', as: :kalibro_range_update
      end
      post '/metric_configurations/new' => 'metric_configurations#new', as: :new_metric_configuration
      put '/metric_configurations/:id' => 'metric_configurations#update', as: :metric_configuration_update

      resources :compound_metric_configurations, except: [:destroy, :update]
      put '/compound_metric_configurations/:id' => 'compound_metric_configurations#update', as: :compound_metric_configuration_update

      resources :hotspot_metric_configurations, only: [:create]
    end

    resources :reading_groups do
      resources :readings, except: [:index, :update, :show]
      put '/readings/:id' => 'readings#update', as: :reading_update
    end

    post '/modules/:id/metric_history' => 'modules#metric_history', as: 'module_metric_history'
    post '/modules/:id/tree' => 'modules#load_module_tree', as: 'module_tree'

    root "home#index"
  end

end

prezento/app/models/project.rb
class Project < KalibroClient::Entities::Processor::Project
  include KalibroRecord
  include HasOwner

  attr_writer :attributes

  def attributes
    @attributes ||= ProjectAttributes.find_by_project_id(@id)
  end

  def destroy
    self.attributes.destroy unless self.attributes.nil?
    @attributes = nil
    super
  end
end

prezento/app/controllers/projects_controller.rb
include OwnershipAuthentication

class ProjectsController < ApplicationController
  before_action :authenticate_user!,
    except: [:index, :show]
  before_action :project_owner?, only: [:edit, :update, :destroy]

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.public_or_owned_by_user(current_user)
  end

  # POST /projects
  # POST /projects.json
  def create
    image_url = project_params.delete(:image_url)
    @project = Project.new(project_params)
    respond_to do |format|
      create_and_redir(format)
      @project.attributes.update(image_url: image_url) unless @project.attributes.nil?
    end
  end

  # GET /project/1
  # GET /project/1.json
  def show
    set_project
    @project_repositories = @project.repositories if @project.is_a?(Project)
  end

  # GET /projects/1/edit
  # GET /projects/1/edit.json
  def edit
    set_project
  end

  def update
    set_project
    image_url = project_params.delete(:image_url)
    if @project.update(project_params) && @project.attributes.update(image_url: image_url)
      redirect_to(project_path(@project.id))
    else
      render "edit"
    end
  end

  # DELETE /project/1
  # DELETE /project/1.json
  def destroy
    set_project
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id].to_i)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params[:project][:name].strip!
    params[:project]
  end

  # Extracted code from create action
  def create_and_redir(format)
    if @project.save
      current_user.project_attributes.create(project_id: @project.id)
      format.html { redirect_to project_path(@project.id), notice: t('successfully_created', :record => t(@project.class.name)) }
      format.json { render action: 'show', status: :created, location: @project }
    else
      format.html { render action: 'new' }
      format.json { render json: @project.likeno_errors, status: :unprocessable_entity }
    end
  end
end

prezento/app/helpers/projects_helper.rb
module ProjectsHelper
  def project_owner? project_id
    user_signed_in? && !current_user.project_attributes.find_by_project_id(project_id).nil?
  end

  def project_image_html(project)
    url = project.attributes.image_url

    if url && !url.empty?
      image_tag url, size:"128x128"
    else
      "<center><i class='fa fa-file-image-o fa-5x'></i></center><br />
       #{t('no_image_available')}".html_safe
    end
  end
end

prezento/app/views/projects/_form.html.erb
<%= form_for(@project, :html => { role: 'form' }) do |f| %>
  <%= render :partial => 'shared/form_errors', :locals => {:object => @project} %>
  <div class="row margin-left-none">
    <div class="form-table col-md-9">
      <div class="form-row">
        <div class="field-container">
          <%= f.label :name, class: 'control-label' %><br>
          <%= f.text_field :name, :required => true, class: 'text-field form-control' %>
        </div>
      </div>
      <div class="form-row">
        <div class="field-container">
          <%= f.label :description, class: 'control-label' %><br>
          <%= f.text_area :description, class: 'text-area form-control' %>
        </div>
      </div>
      <div class="form-row">
        <div class="field-container">
          <%= f.label t("image_url"), class: 'control-label' %><br>
          <%= f.text_field :image_url, class: 'text-area', value: @project.attributes.nil? || @project.attributes.image_url.nil? ? '' : @project.attributes.image_url  %>
        </div>
      </div>
    </div>
  </div>
  <div class="row margin-left-none" style="margin-top: 20px">
    <%= f.submit t('save'), class: 'btn btn-primary' %>
    <%= link_to t('all_projects'), projects_path, class: 'btn btn-default'%>
  </div>
<% end %>

prezento/app/views/projects/edit.html.erb
<div class="page-header">
  <h1><%= t_action(:edit, Project) %></h1>
</div>

<%= render 'form' %>

prezento/app/views/projects/index.html.erb
<div class="page-header">
  <h1><%= "#{Project.model_name.human(count: 2)}" %></h1>
</div>

<% if user_signed_in? %>
  <p>
    <%= link_to t_action(:create, Project), new_project_path, class: 'btn  btn-primary' %>
  </p>
<%else%>
  <p class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= t('unauthenticated', action: t_action(:create, Project, count: 2).downcase) %>
  </p>
<% end %>

<%= render partial: 'shared/project_list', locals: {projects: @projects} %>

prezento/app/views/projects/new.html.erb
<div class="page-header">
  <h1><%= t_action(:create, Project) %></h1>
</div>

<%= render 'form' %>

prezento/app/views/projects/show.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-md-2">
      <%= project_image_html(@project) %>
    </div>
    <div class="col-md-10">
      <h1><%= @project.name %></h1>
    </div>
  </div>
</div>

<p>
  <strong> <%= t("description") %>:</strong>
  <%= @project.description %>
</p>

<hr />

<h2><%= Repository.model_name.human(count: 2) %></h2>

<% if project_owner? @project.id %><%= link_to t_action(:new, Repository), new_project_repository_path(@project,), class: 'btn btn-primary' %><% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t("Name") %></th>
      <th><%= t("Type") %></th>
      <th><%= t("Address") %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% if @project_repositories.size == 0 %>
      <tr>
        <% col_number = project_owner?(@project.id) ? 4 : 3 %>
        <td colspan="<%= col_number %>"> <%= t("no_repositories") %></td>
      </tr>
    <% end %>
    <% @project_repositories.each do |repository| %>
      <tr>
        <td><%= repository.name %></td>
        <td><%= repository.scm_type %></td>
        <td><%= repository.address %></td>
        <td>
          <% if project_owner? @project.id %>
            <%= link_to t('edit'), edit_repository_path(repository.id), class: 'btn btn-info' %>
          <% end %>
        </td>
        <td>
          <%= link_to t('show'), repository_path(repository.id), class: 'btn btn-info' %></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />

<p>
  <% if project_owner? @project.id %>
    <%= link_to t_action(:destroy, Project), project_path(@project.id), method: :delete, data: { confirm: t('want_destroy_project') }, class: 'btn btn-danger' %>
  <% end %>
</p>