prezento/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    devise_for :users
    get 'users/:user_id/projects' => 'users#projects', as: :user_projects

    resources :projects do
      resources :repositories, only: [:new, :create]
    end

    resources :repositories, except: [:update]
    get '/repositories/:id/modules/:module_result_id' => 'repositories#show', as: :repository_module
    get '/repositories/:id/state' => 'repositories#state', as: :repository_state
    get '/repositories/:id/state_with_date' => 'repositories#state_with_date', as: :repository_state_with_date
    put '/repositories/:id' => 'repositories#update', as: :repository_update
    get '/repositories/:id/process' => 'repositories#process_repository', as: :repository_process
    get '/repository_branches' => 'repositories#branches', as: :repository_branches

    scope :format => false, :constraints => { :format => 'json' } do
      post '/repositories/:id/notify_push' => 'repositories#notify_push', as: :repository_notify_push, format: :json
    end

    resources :kalibro_configurations do
      get '/metric_configurations/choose_metric' => 'metric_configurations#choose_metric', as: :choose_metric
      resources :metric_configurations, except: [:update, :new] do
        get '/kalibro_ranges/new' => 'kalibro_ranges#new', as: :new_kalibro_range
        resources :kalibro_ranges, except: [:update, :new]
        put '/kalibro_ranges/:id' => 'kalibro_ranges#update', as: :kalibro_range_update
      end
      post '/metric_configurations/new' => 'metric_configurations#new', as: :new_metric_configuration
      put '/metric_configurations/:id' => 'metric_configurations#update', as: :metric_configuration_update

      resources :compound_metric_configurations, except: [:destroy, :update]
      put '/compound_metric_configurations/:id' => 'compound_metric_configurations#update', as: :compound_metric_configuration_update

      resources :hotspot_metric_configurations, only: [:create]
    end

    resources :reading_groups do
      resources :readings, except: [:index, :update, :show]
      put '/readings/:id' => 'readings#update', as: :reading_update
    end

    post '/modules/:id/metric_history' => 'modules#metric_history', as: 'module_metric_history'
    post '/modules/:id/tree' => 'modules#load_module_tree', as: 'module_tree'

    root "home#index"
  end

end

prezento/app/models/metric_configuration.rb
class MetricConfiguration < KalibroClient::Entities::Configurations::MetricConfiguration
  include KalibroRecord
end

prezento/app/controllers/metric_configurations_controller.rb
class MetricConfigurationsController < BaseMetricConfigurationsController
  before_action :set_reading_groups!, only: [:new, :edit]

  def new
    super
    # The metric parameter comes from the choose metric form
    set_metric!
  end

  def choose_metric
    @metric_collectors_names = KalibroClient::Entities::Processor::MetricCollectorDetails.all_names
  end

  protected

  def metric_configuration_params
    params.require(:metric_configuration).permit(:reading_group_id, :weight, :aggregation_form)
  end

  def metric_type
    'NativeMetricSnapshot'
  end

  private

  def set_reading_groups!
    @reading_groups = ReadingGroup.public_or_owned_by_user(current_user).map do |reading_group|
      [reading_group.name, reading_group.id]
    end
  end
end

prezento/app/helpers/metric_configurations_helper.rb
module MetricConfigurationsHelper
  def aggregation_options
    [[t("aggregation_forms.MEAN"),"MEAN"], [t("aggregation_forms.MEDIAN"), "MEDIAN"], [t("aggregation_forms.MAXIMUM"), "MAXIMUM"], [t("aggregation_forms.MINIMUM"), "MINIMUM"], [t("aggregation_forms.STANDARD_DEVIATION"), "STANDARD_DEVIATION"], [t("aggregation_forms.COUNT"), "COUNT"]]
  end

  def reading_group_options
    ReadingGroup.all.map { |reading_group| [reading_group.name, reading_group.id] }
  end

  def native_metrics_of(kalibro_configuration_id)
    MetricConfiguration.metric_configurations_of(kalibro_configuration_id).map do |metric_configuration|
      [ metric_configuration.metric.code, metric_configuration.metric.name ]
    end
  end

  def supported_metrics_of(metric_collector_name)
    # find_by_name throws an exception instead of returning nil, unlike ActiveRecord's API
    KalibroClient::Entities::Processor::MetricCollectorDetails.find_by_name(metric_collector_name).supported_metrics
  end

  def choose_metric_path(metric, kalibro_configuration_id)
    if metric.type == 'HotspotMetricSnapshot'
      kalibro_configuration_hotspot_metric_configurations_path(kalibro_configuration_id: kalibro_configuration_id)
    else
      kalibro_configuration_new_metric_configuration_path(kalibro_configuration_id: kalibro_configuration_id)
    end
  end

  def hotspot_metric_configuration?(metric_configuration)
    metric_configuration.metric.type == 'HotspotMetricSnapshot'
  end
end

prezento/app/views/metric_configurations/_form.html.erb
<%= render :partial => 'shared/form_errors', :locals => {:object => @metric_configuration} %>

<div class="row margin-left-none">
  <div class="form-table col-md-9">

    <div class="form-row">
      <div class="field-container">
        <%= f.label :weight, class: 'control-label' %>
        <%= f.text_field :weight, :required => true, class: 'text-field form-control' %>
      </div>
      <div class="help-container">
        <p>
          <%= t('calculate_weighted_average_html', href: link_to(KalibroModule.model_name.human, "http://mezuro.github.io/tutorial/2016/04/04/tutorial-keywords.html#module", target: "_blank")) %>
        </p>
      </div>
    </div>

    <div class="form-row">
      <div class="field-container">
        <%= f.label :aggregation_form, class: 'control-label' %>
        <%= f.select( :aggregation_form, aggregation_options, {class: 'form-control'} ) %>
      </div>
      <div class="help-container">
        <p>
          <%= t('aggregation_form_helper_html', href: link_to(t('granularity'), "http://mezuro.github.io/tutorial/2016/04/04/tutorial-keywords.html#granularity", target: "_blank")) %>
        </p>
      </div>
    </div>

    <% if @metric_configuration.persisted? %>
      <%= hidden_field_tag(:reading_group_id, @metric_configuration.reading_group_id) %>
      <%= hidden_field_tag(:kalibro_configuration_id, @metric_configuration.kalibro_configuration_id) %>
    <% else %>
        <div class="form-row">
          <div class="field-container">
            <%= f.label :reading_group_id, class: 'control-label' %>
            <%= f.select( :reading_group_id, reading_group_options, {class: 'form-control'} ) %>
          </div>
          <div class="help-container">
            <p>
              <%= t('reading_group_helper_html', href: link_to(ReadingGroup.model_name.human, "http://mezuro.github.io/tutorial/2016/04/04/tutorial-keywords.html#reading-group", target: "_blank")) %>
            </p>
          </div>
        </div>
        <%= f.hidden_field(:kalibro_configuration_id, value: @kalibro_configuration.id) %>
    <% end %>

  </div>
</div>

<%= hidden_field_tag(:metric_name, @metric_configuration.metric.name) %>
<%= hidden_field_tag(:metric_collector_name, @metric_configuration.metric.metric_collector_name) %>

prezento/app/views/metric_configurations/_no_ranges.html.erb
<tr>
<!-- TODO: expand this columns when the user owns the metric configurations and can edit or delete this range -->
<td colspan="3"><%= t('no_models', model: KalibroRange.model_name.human(count: 2)) %></td>
</tr>

prezento/app/views/metric_configurations/_ranges.html.erb
<tr>
  <td>
    <div>
      <a class="popover_element" rel="popover" data-placement="left" data-original-title="Comments" data-content="<%= kalibro_range.comments %>"><span id="comment-icon" class="fa fa-comment"></span></a>
      <span style="color: #<%= kalibro_range.color %>"><%= kalibro_range.label %></span>
    </div>
  </td>
  <td><%= format_boundary(kalibro_range.beginning) %></td>
  <td><%= format_boundary(kalibro_range.end) %></td>
  <td>
    <% if kalibro_configuration_owner? @metric_configuration.kalibro_configuration_id %>
      <%= link_to t('edit'), edit_kalibro_configuration_metric_configuration_kalibro_range_path(
                  @metric_configuration.kalibro_configuration_id, @metric_configuration.id, kalibro_range.id), class: 'btn btn-info' %>
      <%= link_to t('destroy'), kalibro_configuration_metric_configuration_kalibro_range_path(@metric_configuration.kalibro_configuration_id,
      @metric_configuration.id, kalibro_range.id), method: :delete, data: { confirm: t('want_destroy_range') },
      class: 'btn btn-danger' %>
    <% end %>
  </td>
</tr>

prezento/app/views/metric_configurations/choose_metric.html.erb
<div class="page-header">
  <h1><%= t('choose_metric') %></h1>
</div>

<%= form_tag kalibro_configuration_new_metric_configuration_path(@kalibro_configuration.id) do %>
  <%= hidden_field_tag(:metric_collector_name,) %>
  <%= hidden_field_tag(:metric_code) %>
<% end %>

<div id="base-tool-accordion">
 <% @metric_collectors_names.each do |metric_collector_name| %>
      <h3 class="jquery-ui-accordion"><%= metric_collector_name %></h3>
      <div>
        <% supported_metrics_of(metric_collector_name).each do |code, metric| %>
          <%= link_to metric.name, "#",
            onclick: "MetricCollector.choose_metric(\"#{code}\", \"#{metric_collector_name}\", \"#{choose_metric_path(metric, @kalibro_configuration.id)}\");",
              remote: true %><br>
        <% end %>
      </div>
  <% end %>
</div><br />

<%= link_to t('back'), kalibro_configuration_path(@kalibro_configuration.id), class: 'btn btn-default' %>
<%= link_to t('compound_metric'), new_kalibro_configuration_compound_metric_configuration_path(@kalibro_configuration.id), class: 'btn btn-info', id: "link_to_compound" %>


<script type="text/javascript">
  //Loads the accordion
  $(function() {
    $( "#base-tool-accordion" ).accordion({
      heightStyle: "content",
      active: false,
      collapsible: true
    });
  });

  <% if @kalibro_configuration.metric_configurations.blank? %>
    $("#link_to_compound").css("display", "none");
  <% end %>
</script>

prezento/app/views/metric_configurations/edit.html.erb
<div class="page-header">
  <h1><%= t('editing_metric_configuration') %></h1>
</div>

<%= form_for(@metric_configuration, :url => kalibro_configuration_metric_configuration_update_path(@kalibro_configuration.id, @metric_configuration.id), method: :put) do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <div class="row margin-left-none" style="margin-top: 20px">
  	<%= f.submit t('save'), class: 'btn btn-primary' %>
  	<%= link_to t('back'), kalibro_configuration_path(@metric_configuration.kalibro_configuration_id), class: 'btn btn-default' %>
  </div>
<% end %>

prezento/app/views/metric_configurations/new.html.erb
<div class="page-header">
  <h1><%= t('new_metric_configurations') %></h1>
</div>

<p>
  <b><%= t('metric_base_tool_name') %>:</b> <%= @metric_configuration.metric.metric_collector_name %>
</p>

<p>
  <b><%= t('metric') %>:</b> <%= @metric_configuration.metric.name %>
</p>

<p>
  <b><%= t('description') %>:</b> <%= @metric_configuration.metric.description.nil? ? "No description available." : @metric_configuration.metric.description %>
</p>

<p>
  <b><%= t('language') %>:</b> <%= @metric_configuration.metric.languages.to_s %>
</p>

<p>
  <b><%= t('metric_scope') %>:</b> <%= t(@metric_configuration.metric.scope.to_s, scope: 'scopes') %>
</p>

<br>

<%= form_for(@metric_configuration, :url => kalibro_configuration_metric_configurations_path(@kalibro_configuration.id)) do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <div class="row margin-left-none" style="margin-top: 20px">
  	<%= f.submit t('save'), class: 'btn btn-primary' %>
    <%= link_to t('back'),  kalibro_configuration_choose_metric_path(@kalibro_configuration.id), class: 'btn btn-default' %>
	</div>
<% end %>

prezento/app/views/metric_configurations/show.html.erb
<div class="page-header">
  <h1><%=@metric_configuration.metric.name %></h1>
</div>

<p>
  <strong><%= t('metric_base_tool_name') %>:</strong>
  <%= @metric_configuration.metric.metric_collector_name %>
</p>

<p>
  <strong><%= t('code') %>:</strong>
  <%= @metric_configuration.metric.code %>
</p>

<p>
  <strong><%= t('weight') %>:</strong>
  <%= @metric_configuration.weight %>
</p>

<p>
  <strong><%= t('language') %>:</strong>
  <%= @metric_configuration.metric.languages %>
</p>

<p>
  <strong><%= t('metric_scope') %>:</strong>
  <%= t(@metric_configuration.metric.scope.to_s, scope: 'scopes') %>
</p>

<p>
  <strong><%= t('metric_aggregation_form') %>:</strong>
  <%=
    f = @metric_configuration.aggregation_form
    t(f, scope: 'aggregation_forms', default: f)
  %>
</p>

<p>
  <strong><%= t('reading_group_name') %>:</strong>
  <%= @reading_group.name %>
</p>

<p>
  <strong><%= t('description') %>:</strong>
  <% if @metric_configuration.metric.description.blank? %>
    <%= t('no_description_available') %>
  <% else %>
    <%= @metric_configuration.metric.description %>
  <% end %>

</p>
<hr>

<h2><%= KalibroRange.model_name.human(count: 2) %></h2>
<% if kalibro_configuration_owner? @metric_configuration.kalibro_configuration_id %>
  <%= link_to t_action(:add, KalibroRange), kalibro_configuration_metric_configuration_new_kalibro_range_path(@metric_configuration.kalibro_configuration_id,
      @metric_configuration.id), class: 'btn btn-info' %>
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('label') %></th>
      <th><%= t('beginning') %></th>
      <th><%= t('end') %></th>
    </tr>
  </thead>
  <tbody>
    <% if @kalibro_ranges.empty? %>
      <%= render partial: 'no_ranges' %>
    <% else %>
      <%= render partial: 'ranges', collection: @kalibro_ranges, as: :kalibro_range %>
    <% end %>
  </tbody>
</table>

<p>
 <%= link_to t('back'), kalibro_configuration_path(@metric_configuration.kalibro_configuration_id), class: 'btn btn-default' %>
<% if kalibro_configuration_owner? @metric_configuration.kalibro_configuration_id %>
      <%= link_to t_action(:destroy, MetricConfiguration), kalibro_configuration_metric_configuration_path(@metric_configuration.kalibro_configuration_id,
      @metric_configuration.id), method: :delete, data: { confirm: t('want_destroy_metric_configuration') },
      class: 'btn btn-danger' %>
 <% end %>
</p>


<%= javascript_include_tag "popover.js" %>